sudo: required

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - travis_wait 50 docker build -t rpi-haskell-classy .
  - docker tag rpi-haskell-classy tgolson/rpi-haskell-classy:latest
  - docker tag rpi-haskell-classy tgolson/rpi-haskell-classy:7.10.3

script:
  - docker push tgolson/rpi-haskell-classy:latest
  - docker push tgolson/rpi-haskell-classy:7.10.3
